# Extra abstraction on top of your raw tables which can be referenced using this .yml
version: 2

sources:    # Here you give aliases to actual tables in Snowflake, which is what sources is about. 
  - name: airbnb  # Source namespace (database) called airbnb. Callable with e.g. {{source('airbnb', 'listings')}}
    schema: raw # Schema raw
    tables:     # Tables in the database and schema mentioned above
      - name: listings            # Name of the object
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4  # SELECT DISTINCT ROOM_TYPE FROM AIRBNB.DEV.DIM_LISTINGS_CLEANSED; leidt tot slechts 4 room_type's. 
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"  # Waarde moet starten met dollarteken ^, Het dollarteken is een special character in regex, dus moet deze escaped worden. yml gebruikt backslashes echter ook als special character en regex gebruikt backslashes ook om iets te escapen dus om iets daadwerkelijk te escapen moet je twee backslashes achter elkaar gebruiken. Vervolgens moet je nog twee backslashes toevoegen voor Snowflake. Na het testen van de compiled sql in folder target zag je namelijk dat in de compiled sql de backslashes wegvielen. De echte regex is dus: ^\$[0-9][0-9\.]+$

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date   # Check date freshness: can be tested with command "dbt source freshness" in terminal 
        freshness:
            warn_after: {count: 1, period: hour} # Warning when data is an hour old
            error_after: {count: 24, period: hour} # Error when data is 24 hours old



